/*
* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
* By starting with 1 and 2, the first 10 terms will be:
*
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
* By considering the terms in the Fibonacci sequence whose values do not exceed four million,
* find the sum of the even-valued terms.
*/

#include <iostream>

int even_fibonacci_sum(uint);

int main() {
    std::cout << even_fibonacci_sum(4000000) << '\n';
    return 0;
}


int even_fibonacci_sum(uint upper_limit) {
    int first = 1;
    int second = 2;
    int even_fibonacci_sum = 0;
    while(second <= upper_limit) {
        if (second % 2 == 0) even_fibonacci_sum += second;
        int temp = second;
        second += first;
        first = temp;
    }
    return even_fibonacci_sum;
}